### PR TITLE
Including Akka-specific attributes in MDC to match scala Slf4jLogger behavior.

### PR DESCRIPTION
**Pull request by cemcatik**
Includes `sourceThread`, `sourceActorSystem`, `akkaSource`, and `akkaTimestamp` in MDC, which can then be referenced in for example log4net pattern layout like:

```<conversionPattern value="[%-5level][%utcdate][Thread %4t][%logger{1}][%mdc{akkaSource}] %m%n" />```

### CODE REVIEW

**Comment by Danthar** [comment]
Please make this PR against the dev branch.

**Comment by cemcatik** [comment]
Ok, I'll take care of it shortly.

**Comment by cemcatik** [comment]
Should be ready now.

**Comment by Danthar** [comment]
Done. Thx for the contribution. :) Ill so a PR to update to akka 1.2.3 soon. After that we can push to master and get a release out.
Or you could do the PR if you want.

**Comment by cemcatik** [comment]
Thanks so much for the quick turn around. I'll let you update Akka :)

**Comment by Danthar** [comment]
@cemcatik release is pushed, Should be available on nuget in a while.

**Comment by cemcatik** [comment]
@Danthar It works!

**Pull request merged**
